---
layout: custom
---

# R Contributor Site

This is a community-maintained site for people interested in contributing to core R codebase - the code and documentation that gets [distributed as base R](https://cloud.r-project.org).

Join our [Slack Group](slack.qmd) to chat with current and aspiring R contributors. Everyone interested is welcome!

Read the [R Development Guide](https://contributor.r-project.org/rdevguide){target="_blank"}, follow a [Tutorial](tutorials.qmd), or attend an [Event](events.qmd) to learn more about contributing to R.

## Quick Start

Watch the following demo for a 10-minute introduction making a contribution:

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/VOlF8fPf9v8" title="How to Make a Contribution to Base R - CW23 Demo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<br>
The [presentation slides](https://hturner.github.io/contributing-demo/) are available in HTML format - press `S` to view with speaker notes (the video text). 

The demo introduces a basic workflow for simple fixes. For more complex work on internal R functions or compiled code (e.g. involving the C code underlying much of base R), it will be necessary to build R to develop and test your patch. The R Development Guide provides more information on [building R from source](https://contributor.r-project.org/rdevguide/chapters/getting_started.html) and [the lifecycle of a patch](https://contributor.r-project.org/rdevguide/chapters/lifecycle_of_a_patch.html).

## About 

This site is maintained by the [R Contribution Working Group](working-group.qmd), which is working on initiatives to encourage wider contribution to R core. The working group is open to new members ([more information](working-group.qmd)). You can report issues about this website on the [r-devel.github.io](https://github.com/r-devel/r-devel.github.io) repository.
