---
title: "Resources for General Help with R"
---

## Dedicated channels for R help

For help on topics that are not related to contributing to R, please post on one of the following:

 * [R-help](https://stat.ethz.ch/mailman/listinfo/r-help) - general Q&A about using R
 * [R-pkg-devel](https://stat.ethz.ch/mailman/listinfo/r-help) - Q&A about developing R packages
 * [Special Interest Groups](https://www.r-project.org/mail.html#special-interest-groups) - Q&A related to specific topics (and R), e.g. mixed models, high-performance computing, Debian.
 * [Bioconductor support form](https://support.bioconductor.org/) - Q&A related to using/developing Bioconductor packages
 * [Posit community forum](https://community.rstudio.com/categories) - Q&A related to the RStudio IDE and packages maintained by Posit, e.g. tidyverse, Shiny.
 * [rOpenSci forum](https://discuss.ropensci.org/) - Q&A related to rOpenSci packages and projects (e.g. r-universe).
 * [R for Data Science (R4DS) Slack](https://www.rfordatasci.com/) - help with topics from the R4DS book, but also using R/programming in R more generally.
 * [Stackoverflow](https://stackoverflow.com/) - help with very specific queries, use the [r] tag.
 
## General R communities

Posts about R can be found with the #RStats tag on social media such as Mastodon, X, etc. Sometimes posting about an issue can be an effective way to find help.

 * [The R Project for Statistical Computing LinkedIn Group](https://www.linkedin.com/groups/77616/) - a community-run private discussion group for R users
 * [discoRd](https://discord.gg/p4VezC9B) - a Discord server for text or voice chat with other R users. Many specialized channels (e.g. finance, R markdown, machine learning) as well as general R and non-R chat.
 * [grrr](https://github.com/frrrenchies/frrrenchies?tab=readme-ov-file#cat-chat-et-discussions-instantan%C3%A9es-cat) - French-speaking R Users Slack.
 
## R communities for members of underrepresented groups

There are several communities for members of groups that are underrepresented in the global R community. Many have Slack groups, sometimes with specific channels to ask for help with R.

 * [R-Ladies community Slack](https://airtable.com/appJZFYABfCIdPYMR/pagw7FJB5tm2UQ55o/form) - general help with R on #r-help channel, Slack group is for women and gender minorities only.
 * [RainbowR community Slack](https://docs.google.com/forms/d/1y7SOWE3IW-fpR_5Cd4mK-CMUpFZ-hvhY4cTj34JqTVE/viewform?edit_requested=true) - supporting LGBTQ+ people who code in the R language.
 * [Minorities in R community Slack](https://mircommunity.com/about/) - supporting R users from marginalized races, genders, and the disabled community.
 
## Regional R communities

 * [AsiaR Discord](https://discord.gg/rdd8Wrj6) - supporting R users from or living in Asia.
    * [Korea R User Group Discord](https://discord.gg/BwesHQe8yU) - supporting R users from or living in Korea.
 * [LatinR Slack](https://latin-r.slack.com/join/shared_invite/enQtNDA3MjM3MTQwOTM1LTg3ZWMyNWU3MGI2MGM5YzU0MGU4NWE5NjYwMjBhMGZmYTQzYTA0ODZlOTE1NDc0YzIwM2NhYTJiNDQyZjMzZjc#/shared-invite/email) - supporting R users from or living in Latin America. Use the #r-ajuda-r-ayuda channel to get help in Spanish, (Brazilian) Portuguese or English.
 
 

