---
title: "R Contribution Working Group"
---

The R Contribution Working Group is a collaboration between R Core, R community groups (including [Forwards](https://forwards.github.io/), the [R Community Diversity and Inclusion Working Group](https://github.com/RConsortium/RCDI-WG/tree/master), [R-Ladies](https://rladies.org/), [MiR](https://mircommunity.com/)) and members of the wider R community. Its aim is to encourage new contributors to R core, with a focus on diversity and inclusion.

## Current Work

The group maintains the [r-devel/rcwg](https://github.com/r-devel/rcwg) repository, with issues relating to current initiatives and related documents, such as minutes of meetings.

## Get Involved

Anyone from the R community that supports the group's objectives and would like to contribute is welcome to get involved. This can range from commenting on GitHub issues to actively working on initiatives.

To communicate with the group:
 - Attend an RCWG meeting (details below) or add an item to the [collaborative agenda](https://hackmd.io/@hturner/HyISuE97D/edit).
 - Open an issue on the [r-devel/rcwg](https://github.com/r-devel/rcwg) repository.
 - Post a message on the #core-outreach channel of the [R Contributors Slack](slack) (preferred) or email the group chair, [Heather Turner](mailto:heather.turner@r-project.org). 
 
The RCWG meet (on Zoom) every 1-2 months, usually alternating between the third Friday of the month, 15:00 UTC and the third Tuesday of the month, 19:30 UTC (-1hr during Daylight Savings Time in Europe). Stay up-to-date with meeting announcements in one of the following ways:
 - Go to the [Events](events) page and add the event series to your calendar.
 - Join the [R Contribution Working Group mailing list](https://stat.ethz.ch/mailman/listinfo/r-contribution-wg) to stay up-to-date with working group activities.
