---
title: "Tutorials & Demos"
---

These tutorials and demos are designed to help new contributors get started.

## Tutorials

Video tutorials with integrated/additional exercises.

<ul>
<li>
<a href= "/tutorials/contributing-to-r">Contributing to R</a>,
<i>Gabriel Becker and Martin Maechler, useR! 2021.</i>  
2h15 video (or 1h30 abridged version), with accompanying slides and exercises.
<details><summary>Abstract</summary>
Did you always want to contribute to (base) R but don't know how?

This tutorial shows cases where and how users have contributed actively to (base) R, by submitting bug reports with minimal reproducible examples, how testing, reading source code, and providing patches to the R source code has helped making R better.

A selection of past bug reports are provided for you to practice debugging. For bugs that have been resolved you can check what happened after the bug was reported.
</details>
</li>
<li>
<a href= "/tutorials/translating-r-to-your-language">Translating R to your Language</a>,
<i>Michael Chirico and Michael Lawrence, useR! 2021.</i>  
1h30 video with accompanying slides.
<details><summary>Abstract</summary>
R users are a global bunch. Providing error messages in languages besides English can greatly improve the user experience (and debugging experience) of those using R who may not be English natives.

The standard tools for providing translations can be somewhat esoteric; this tutorial goes over some of the challenges presented by translations, the process for providing and/or updating translations to R itself, and finally introduces a package (potools) that will remove some of the frictions potential translators may face.
</details>
</li>
</ul>

## Demos

Short videos to give people a quick start on the basics.

<ul>
<li>
<a href= "/demos/how-to-make-a-contribution-to-base-r">How to Make a Contribution to Base R</a>, 
<i>Heather Turner and Ella Kaye, Collaborations Workshop 2023.</i> 
10 min video.
<details><summary>Abstract</summary>
Making a contribution to a large open source software project like the R project can seem very daunting. This walkthrough aims to demonstrate how R users can contribute simple fixes to the code or documentation in base R, helping to maintain this fundamental software for data science. We will briefly look at: 1) How to find a good bug to work on, 2) Getting to the the root of the issue, and 3) How to propose a fix.
</details>
</li>
<li>
<a href= "/demos/latinr-hackathon">R translatón / Hackaton de tradução do R</a>, 
<i>Beatriz Milz, Ángela Sanzo, and Macarena Quiroga, LatinR 2022.</i> 
40 min video (mainly in Spanish)
<details><summary>Abstract</summary>
This is a video recording of the start of the R translatón / Hackaton de tradução do R at LatinR 2022. There is a short presentation giving background on translating R's messages, warnings and errors, followed by a demonstration of using the R Project Weblate server.
</details>
</li>
</ul>