---
layout: custom
---

# Contributing to R

In this video tutorial recorded at useR! 2021, Gabriel Becker and Martin Maechler explain how members of the R community can contribute to R.

The full video (2h15) includes Gabriel discussing his experiences as an external contributor: some of the projects he has worked on and lessons learned. This is recommended for all aspiring contributors as a window into the social dynamics of contribution.

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/CZmldTOdlRM" title="Contributing to R" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>
If you are short on time, the abridged video (1h30) focuses on the starting point for most contributors: helping address bugs in R.

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/tsymQiL2BY0" title="Contributing to R (abridged)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>
The [tutorial presentation slides](https://github.com/gmbecker/contributing_to_r_lesson/blob/master/outline.pdf) are available in PDF format (the abridged version skips slides 12-45).

The [Contributing to R GitHub repository](https://github.com/gmbecker/contributing_to_r_lesson) provides links to background reading and exercises based on real bugs in R 3.3.2. A docker image is provided, alternatively on Windows you can install the [R 3.3.2 binary](https://cran-archive.r-project.org/bin/windows/base/old/3.3.2/).
