---
layout: custom
---

# Translating R to your language

In this video tutorial recorded at useR! 2021, Michael Chirico and Michael Lawrence aim to get package developers and other R community members started implementing foreign-language translations of R's messages (errors, warnings, verbose output, etc.) into a language of their choosing.

Our real-time participants were focused on Spanish, Bahasa Indonesia, and Hungarian.

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/S3Qhqf9u6ao" title="Translating R to your language" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

<br> The [tutorial presentation slides](https://docs.google.com/presentation/d/16700QHu2YbqK0zCukscSqBOUtTMBAxsa_U7xEUWbT8o/edit#slide=id.p) are publicly available in Google Slides format.

*Note: This video describes the [gettext](https://www.gnu.org/software/gettext/) infrastructure that R uses to internationalize messages. This background information and the tips for translation (first 1h15 of video) are still relevant, but we now recommend translations are added/updated via the [R Project Weblate server](https://translate.rx.studio/projects/r-project/).*
